### ISSUE TITLE
Georgia Tech - GRE requirement

### ISSUE THREAD

**Issue by siddarth-c** [WillMartin7/gre-requirements#4]
This link states GRE to be a requirement: https://www.cc.gatech.edu/academics/degree-programs/masters/computer-science/admissionreqs

Could you verify this?

**Comment by willcmartin** [comment]
Thanks for pointing this out. This source has the test as optional: [link](https://grad.gatech.edu/degree-programs/computer-science-campus). I updated the list to say optional, but added your link as well in notes. Someone on Reddit said they are reaching out to the school for more info. I'll update the sheet when I hear back.

**Comment by WillMartin7** [comment]
It looks like this has been updated on the website so I am closing this issue. 

MS- Required, Ph.D.- Optional

**Comment by willcmartin** [comment]
It looks like this has been updated on the website so I am closing this issue. 

MS- Required, Ph.D.- Optional
