### ISSUE TITLE
Columbia CS Requirements

### ISSUE THREAD

**Issue by yogeshr59** [WillMartin7/gre-requirements#7]
For Columbia CS. Nothing is mentioned in the given link about GRE being waived off.

Though, it is clearly mentioned for Fall 2021 in the following links: 

- https://www.gradengineering.columbia.edu/graduate-admissions/application-requirements#:~:text=Official%20Graduate%20Record%20Examination%20(GRE)%20General%20Test%20Scores

- https://www.cs.columbia.edu/education/ms/appfaq/#:~:text=The%20Graduate%20Record%20Examination%20(GRE)%20is%20not%20required%20for%202021%20admission%20cycle.

**Comment by willcmartin** [comment]
Thanks for taking a deeper look at this. You're correct, I made a mistake on the Master's program requirement. I will update it to "required" as it looks like, according to your links, it was waived for Fall 2021 but has not been waived (at least not yet) for Fall 2022.
